### ISSUE TITLE
Error while trying to run it on Windows 

### ISSUE THREAD

**Issue by BurgaoTheChamp** [Turbodesigner/parafoil#21]
it did created the simulation_out directory. I had to input SU2 8.0.0 as custom executable path and I found a mistype on Paraflow->su2.py that is typed "win " instead of "win"

![Screenshot 2023-09-03 201309 - Copy](https://github.com/OpenOrion/parafoil/assets/94881470/753cb728-e95e-42a7-8da2-b5f5fc3646df)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 10
      8 use_cache = False
      9 if not use_cache:
---> 10     sim_results = run_simulation(
     11         passage,
     12         sim_options=SimulationOptions(
     13             inlet_total_state=inlet_total_state, 
     14         ),
     15         working_directory=".\simulation_out", 
     16         id="1",
     17         auto_delete=False,
     18         sim_config={
     19             "custom_executable_path": "C:\simulators\su2\SU2-v8.0.0-win64\in\SU2_CFD.exe"
     20         }
     21     )
     22     sim_results.to_file("sim_results.pkl")
     23 else:

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\paraflow\simulation\simulation.py:26, in run_simulation(passage, sim_options, working_directory, id, sim_type, auto_delete, verbose, num_procs, sim_config)
     24 if sim_type == 'su2':
     25     from paraflow.simulation.su2 import run_su2_simulation
---> 26     sim_results = run_su2_simulation(meshes, config, config_path, auto_delete, verbose, num_procs, **sim_config)
     28 return sim_results

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\paraflow\simulation\su2.py:147, in run_su2_simulation(meshes, config, config_path, auto_delete, verbose, num_procs, install_dir, version, custom_download_url, custom_repo_url, custom_mpirun_path, custom_executable_path)
    144         vtu_filename = vtu_filename.replace(".", f"_{i}.")
    146     grids += [read_vtu_data(vtu_filename)]
--> 147 eval_values = pd.read_csv(config["CONV_FILENAME"])
    150 if auto_delete:
    151     delete_output_files(config, config_path, num_zones)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:912, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    899 kwds_defaults = _refine_defaults_read(
    900     dialect,
    901     delimiter,
   (...)
    908     dtype_backend=dtype_backend,
    909 )
    910 kwds.update(kwds_defaults)
--> 912 return _read(filepath_or_buffer, kwds)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:577, in _read(filepath_or_buffer, kwds)
    574 _validate_names(kwds.get("names", None))
    576 # Create the parser.
--> 577 parser = TextFileReader(filepath_or_buffer, **kwds)
    579 if chunksize or iterator:
    580     return parser

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:1407, in TextFileReader.__init__(self, f, engine, **kwds)
   1404     self.options["has_index_names"] = kwds["has_index_names"]
   1406 self.handles: IOHandles | None = None
-> 1407 self._engine = self._make_engine(f, self.engine)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:1661, in TextFileReader._make_engine(self, f, engine)
   1659     if "b" not in mode:
   1660         mode += "b"
-> 1661 self.handles = get_handle(
   1662     f,
   1663     mode,
   1664     encoding=self.options.get("encoding", None),
   1665     compression=self.options.get("compression", None),
   1666     memory_map=self.options.get("memory_map", False),
   1667     is_text=is_text,
   1668     errors=self.options.get("encoding_errors", "strict"),
   1669     storage_options=self.options.get("storage_options", None),
   1670 )
   1671 assert self.handles is not None
   1672 f = self.handles.handle

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\common.py:859, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    854 elif isinstance(handle, str):
    855     # Check whether the filename is to be opened in binary mode.
    856     # Binary mode does not support 'encoding' and 'newline'.
    857     if ioargs.encoding and "b" not in ioargs.mode:
    858         # Encoding
--> 859         handle = open(
    860             handle,
    861             ioargs.mode,
    862             encoding=ioargs.encoding,
    863             errors=errors,
    864             newline="",
    865         )
    866     else:
    867         # Binary mode
    868         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: 'e:\\Coding\\Test_Parafoil\\simulation_out/history1.csv'

![Screenshot 2023-09-03 201358 - Copy](https://github.com/OpenOrion/parafoil/assets/94881470/46677f52-d659-4157-946c-6a73663373a7)

**Comment by afshawnlotfi** [comment]
Okay so this was the circular passage edge case and everything was the same except this was in Windows, correct?

**Comment by BurgaoTheChamp** [comment]
yes, correct

**Comment by afshawnlotfi** [comment]
Thanks, looking into this further

**Comment by afshawnlotfi** [comment]
Was able to recreate, problem seems to be Windows newlines are different 🙄. When in doubt just run the executable on the config file it generates and debug from there. I will try and have a fix up by tonight.

**Comment by BurgaoTheChamp** [comment]
Ok, thank you!
Let me know when you fix it, I'm really eager to try it!

**Comment by afshawnlotfi** [comment]
> Ok, thank you! Let me know when you fix it, I'm really eager to try it!

Hey sorry for the delay, LONG week.
Please let me know if it works for you on this branch: https://github.com/OpenOrion/parafoil/tree/win-support

**Comment by BurgaoTheChamp** [comment]
It didn't work :/
same error!
I have both paraflow and parafoil on the win-support branch...

**Comment by afshawnlotfi** [comment]
> It didn't work :/ same error! I have both paraflow and parafoil on the win-support branch...

Oof sorry about that, some additional changes in the VM for paraflow that I forgot to transfer. Try again now.

**Comment by BurgaoTheChamp** [comment]
Still have the error :/

**Comment by afshawnlotfi** [comment]
> Still have the error :/

I guarantee you you have an old version of paraflow at this point. Do `pip uninstall paraflow` and `pip install -r requirements_dev.txt` Also delete the `simulators` folder in the Home directory. I have run this on a fresh Windows VM so if it still doesn't work I don't really have a time to debug with you.

Also git pull on the parafoil repo for the win-support branch

**Comment by afshawnlotfi** [comment]
Oh updated the setup.py if you are doing a direct install instead of dev setup. Had the old paraflow

**Comment by BurgaoTheChamp** [comment]
I was using pip install to update it, parafoil installed the branch 3.1.0 and paraflow installed the branch 3.0.0 even if I explicit input 3.1.0, I found it weird so I decide to uninstall both and run it from home folder, both on version 3.1.0. 
I tried the simulation.ipynb from paraflow example.
Still got the error, simulators folder wasn't created also Python Kernel still crashes.
I'm going to try on other machine later if still behaves as this. 

Setting up SU2 Simulation for [e:\Coding\Test_Parafoil\simulation_out/config1.cfg](file:///E:/Coding/Test_Parafoil/simulation_out/config1.cfg)
Running SU2 Simulation for [e:\Coding\Test_Parafoil\simulation_out/config1.cfg](file:///E:/Coding/Test_Parafoil/simulation_out/config1.cfg)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[e:\Coding\Test_Parafoil\simulation.ipynb](file:///E:/Coding/Test_Parafoil/simulation.ipynb) Cell 8 line 6
      [3](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=2) use_cache = False
      [5](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=4) if not use_cache:
----> [6](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=5)     sim_results = run_simulation(
      [7](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=6)         passage,
      [8](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=7)         params=SimulationParams(
      [9](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=8)             inlet_total_state=inlet_total_state, 
     [10](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=9)             target_outlet_static_state=target_outlet_static_state, 
     [11](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=10)         ),
     [12](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=11)         working_directory="[./simulation_out](https://file+.vscode-resource.vscode-cdn.net/e%3A/Coding/Test_Parafoil/simulation_out)", 
     [13](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=12)         id="1",
     [14](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=13)         auto_delete=True,
     [15](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=14)         verbose=False,
     [16](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=15)     )
     [17](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=16)     sim_results.to_file("sim_results.pkl")
     [18](vscode-notebook-cell:/e%3A/Coding/Test_Parafoil/simulation.ipynb#X10sZmlsZQ%3D%3D?line=17) else:

File [e:\Coding\Test_Parafoil\paraflow\simulation\simulation.py:23](file:///E:/Coding/Test_Parafoil/paraflow/simulation/simulation.py:23), in run_simulation(passage, params, working_directory, id, auto_delete, verbose, num_procs, cfg)
     21 if isinstance(cfg, Su2SimulationConfig):
     22     from paraflow.simulation.su2 import run_su2_simulation
---> 23     sim_results = run_su2_simulation(passage, params, working_directory, id, auto_delete, verbose, num_procs, cfg)
     25 return sim_results

File [e:\Coding\Test_Parafoil\paraflow\simulation\su2.py:156](file:///E:/Coding/Test_Parafoil/paraflow/simulation/su2.py:156), in run_su2_simulation(passage, params, working_directory, id, auto_delete, verbose, num_procs, cfg)
    153         vtu_filename = vtu_filename.replace(".", f"_{i}.")
    155     grids += [read_vtu_data(vtu_filename)]
--> 156 eval_values = pd.read_csv(config["CONV_FILENAME"])
    159 if auto_delete:
    160     delete_output_files(config, config_path, num_zones)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:912, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    899 kwds_defaults = _refine_defaults_read(
    900     dialect,
    901     delimiter,
   (...)
    908     dtype_backend=dtype_backend,
    909 )
    910 kwds.update(kwds_defaults)
--> 912 return _read(filepath_or_buffer, kwds)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:577, in _read(filepath_or_buffer, kwds)
    574 _validate_names(kwds.get("names", None))
    576 # Create the parser.
--> 577 parser = TextFileReader(filepath_or_buffer, **kwds)
    579 if chunksize or iterator:
    580     return parser

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:1407, in TextFileReader.__init__(self, f, engine, **kwds)
   1404     self.options["has_index_names"] = kwds["has_index_names"]
   1406 self.handles: IOHandles | None = None
-> 1407 self._engine = self._make_engine(f, self.engine)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\parsers\readers.py:1661, in TextFileReader._make_engine(self, f, engine)
   1659     if "b" not in mode:
   1660         mode += "b"
-> 1661 self.handles = get_handle(
   1662     f,
   1663     mode,
   1664     encoding=self.options.get("encoding", None),
   1665     compression=self.options.get("compression", None),
   1666     memory_map=self.options.get("memory_map", False),
   1667     is_text=is_text,
   1668     errors=self.options.get("encoding_errors", "strict"),
   1669     storage_options=self.options.get("storage_options", None),
   1670 )
   1671 assert self.handles is not None
   1672 f = self.handles.handle

File [c:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\pandas\io\common.py:859, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    854 elif isinstance(handle, str):
    855     # Check whether the filename is to be opened in binary mode.
    856     # Binary mode does not support 'encoding' and 'newline'.
    857     if ioargs.encoding and "b" not in ioargs.mode:
    858         # Encoding
--> 859         handle = open(
    860             handle,
    861             ioargs.mode,
    862             encoding=ioargs.encoding,
    863             errors=errors,
    864             newline="",
    865         )
    866     else:
    867         # Binary mode
    868         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: 'e:/Coding/Test_Parafoil/simulation_out/history1.csv'

![Screenshot 2023-09-17 133048](https://github.com/OpenOrion/parafoil/assets/94881470/39702b7e-cf04-4961-9049-092b203aa7a8)

**Comment by BurgaoTheChamp** [comment]
I think i found the issue...
First it's not able to download the 7.5.1
And if i change it 8.0.0, which is the newest version it does download whoever it gets corrupted somehow because when i change it back to .zip it's not the same file in su2code releases.

another issue that i found when it replaces the ".zip" from the SU2 file it downloads for "" and runs it. That isn't right!? I think it should "extract" the zip file, go into bin folder and then run the SU2_CFD.exe, correct me if i'm wrong?

**Comment by BurgaoTheChamp** [comment]
Happens when i set the parameter Check=True

![image](https://github.com/OpenOrion/parafoil/assets/94881470/b6fc27a9-f613-4729-9d54-e5aee6acd3b6)

**Comment by BurgaoTheChamp** [comment]
I found the source of the issue 
![image](https://github.com/OpenOrion/parafoil/assets/94881470/8276ac76-7078-44c7-bdbb-d4c05dbabf34)
You can't set directories inside the .cfg and the command also needs to be run inside the directory where the .cfg is located.. idk why but it's odd

**Comment by BurgaoTheChamp** [comment]
dude the issue was that i was using the e:\\ directory instead of c:\\ directory and your code was replacing c:\\ directory instead of e:\\ directory so it's not replacing it properly
![image](https://github.com/OpenOrion/parafoil/assets/94881470/4bd7ca91-5c9d-4af0-987b-2dc09a78e116)

**Comment by afshawnlotfi** [comment]
Hey sorry for being AFK on this. This week has been super busy. Honestly this was super lazy on my end. I'll do a better approach, however, use this approach for now.

**Comment by afshawnlotfi** [comment]
Now on mainline, sorry for delay was busy with other priorities
